#
# The contents of this file are subject to the University of Utah Public
# License (the "License"); you may not use this file except in
# compliance with the License.
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied.  See
# the License for the specific language governing rights and limitations
# under the License.
#
# The Original Source Code is "teem", released March 23, 2001.
#  
# The Original Source Code was developed by the University of Utah.
# Portions created by UNIVERSITY are Copyright (C) 2001, 1998 University
# of Utah. All Rights Reserved.
#
#
LIB = ten
HEADERS = ten.h tenMacros.h
LIB_OBJS = tensor.o chan.o aniso.o glyph.o methods.o
#TEST_BINS = test/chan2tens test/anisos test/boxes test/anisovol test/slices
TEST_BINS = test/chan2tens test/anisos test/anisovol test/es
BINS = 
BIN_LIBS = -lten -llimn -ldye -lnrrd -lell -lbiff -lair -lm

include ../make/Common.mk
