# This variable will help provide a master list of all the sources.
# Add new source files here.
SET(TEN_SOURCES
  aniso.c
  bimod.c
  bvec.c
  triple.c
  chan.c
  defaultsTen.c
  enumsTen.c
  epireg.c
  estimate.c
  fiber.c
  fiberMethods.c
  glyph.c
  grads.c
  miscTen.c
  mod.c
  tenGage.c
  tenDwiGage.c
  tensor.c
  qseg.c
  path.c
  qglox.c
  tendAnhist.c
  tendAnplot.c
  tendAnscale.c
  tendAnvol.c
  tendBfit.c
  tendBmat.c
  tendEllipse.c
  tendEpireg.c
  tendEstim.c
  tendEval.c
  tendEvaladd.c
  tendEvalclamp.c
  tendEvalpow.c
  tendEvec.c
  tendEvecrgb.c
  tendEvq.c
  tendExpand.c
  tendFiber.c
  tendFlotsam.c
  tendGlyph.c
  tendGrads.c
  tendHelix.c
  tendMake.c
  tendNorm.c
  tendPoint.c
  tendSatin.c
  tendShrink.c
  tendSim.c
  tendSlice.c
  tendSten.c
  tendUnmf.c
  tendLog.c
  tendExp.c
  )

ADD_TEEM_LIBRARY(ten ${TEN_SOURCES})
