LIB = 
HEADERS = 
LIBOBJS = 
TEST_BINS = 
BINS = crop histo histax permute slice xsect stitch \
	2a arith heq median nconvert quantize project mhisto
BINLIBS = -lnrrd -lbiff -lair -lm

include ../make/Common.mk
