#
# Teem: Tools to process and visualize scientific data and images
# Copyright (C) 2009--2022  University of Chicago
# Copyright (C) 2008, 2007, 2006, 2005  Gordon Kindlmann
# Copyright (C) 2004, 2003, 2002, 2001, 2000, 1999, 1998  University of Utah
#
# This library is free software; you can redistribute it and/or modify it under the terms
# of the GNU Lesser General Public License (LGPL) as published by the Free Software
# Foundation; either version 2.1 of the License, or (at your option) any later version.
# The terms of redistributing and/or modifying this software also include exceptions to
# the LGPL that facilitate static linking.
#
# This library is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License along with
# this library; if not, write to Free Software Foundation, Inc., 51 Franklin Street,
# Fifth Floor, Boston, MA 02110-1301 USA

# halt if python2; thanks to https://preview.tinyurl.com/44f2beza
_x,*_y=1,2 # NOTE: A SyntaxError here means you need python3, not python2
del _x, _y

# For more about teem.py, its functionality, and how it is created,
# see teem/python/cffi/README.md

import math # for math.isnan test
import sys as _sys
if _sys.platform == 'darwin':  # mac
    _lpathVN = 'DYLD_LIBRARY_PATH'
    _shext = 'dylib'
else:
    _lpathVN = 'LD_LIBRARY_PATH'
    _shext = 'so'

try:
    import _teem
except ModuleNotFoundError:
    print('\n*** teem.py: failed to load shared library wrapper module "_teem", from')
    print('*** a shared object file named something like _teem.cpython-platform.so.')
    print('*** Make sure you first ran: "python3 build_teem.py" to build that,')
    print(f'*** and/or try setting the {_lpathVN} environment variable so that')
    print(f'*** the underlying libteem.{_shext} shared library can be found.\n')
    raise

# The value of this ffi, as opposed to "from cffi import FFI; ffi = FFI()" is that it knows
# about the various typedefs that were learned to build the CFFI wrapper, which may in turn
# be useful for setting up calls into libteem
ffi = _teem.ffi
# enable access to original un-wrapped things, straight from cffi
lib = _teem.lib
# for slight convenience, e.g. when calling nrrdLoad with NULL (default) NrrdIoState
NULL = ffi.NULL
# NOTE that "ffi", "lib" and "NULL" are currently the only things "exported" by this module
# that are not either a CFFI-generated wrapper for a C symbol in the libteem library, or an
# extra Python wrapper around that wrapper (as with biff-using functions, and teemEnums)

# this is an experiment
class teemEnum:
    """A helper/wrapper around airEnums (or pointers to them) in Teem, which
    provides convenient ways to convert between integer enum values and real
    Python strings. The C airEnum underlying the Python teemEnum foo is still
    available as both foo.ae and foo().
    """
    def __init__(self, ae):
        """Constructor takes a Teem airEnum pointer (const airEnum *const)."""
        self.ae = ae
        if not str(ae).startswith("<cdata 'airEnum *' "):
            raise TypeError(f'passed argument {ae} does not seem to be a Teem airEnum pointer')
        self.name = _teem.ffi.string(self.ae.name).decode('ascii')
        # looking at airEnum struct definition in air.h
        self.vals = list(range(1, self.ae.M + 1))
        if self.ae.val:
            self.vals = [self.ae.val[i] for i in self.vals]
    def __call__(self):
        """Returns (a pointer to) the underlying Teem airEnum."""
        return self.ae
    def __iter__(self):
        """Provides a way to iterate through the valid values of the enum"""
        return iter(self.vals)
    def str(self, v: int):
        """Converts from integer enum value v to string identifier
        (wraps airEnumStr())"""
        return _teem.ffi.string(_teem.lib.airEnumStr(self.ae, v)).decode('ascii')
    def desc(self, v: int):
        """Converts from integer value v to description string
        (wraps airEnumDesc())"""
        return _teem.ffi.string(_teem.lib.airEnumDesc(self.ae, v)).decode('ascii')
    def val(self, s: str):
        """Converts from string s to integer enum value
        (wraps airEnumVal())"""
        return _teem.lib.airEnumVal(self.ae, s.encode('ascii'))
    def unknown(self):
        """Returns value representing unknown
        (wraps airEnumUnknown())"""
        return _teem.lib.airEnumUnknown(self.ae)

# The following dictionary is for all of Teem, including functions from the
# "experimental" libraries; it is no problem if the libteem in use does not
# actually contain the experimental libs.
# (the following generated by teem/src/_util/buildBiffDict.py)
def _equalsOne(x): return x == 1
_biffDict = {
    'nrrdArrayCompare': (_equalsOne, 0, b'nrrd', 'nrrd/accessors.c:518'),
    'nrrdApply1DLut': (_equalsOne, 0, b'nrrd', 'nrrd/apply1D.c:434'),
    'nrrdApplyMulti1DLut': (_equalsOne, 0, b'nrrd', 'nrrd/apply1D.c:465'),
    'nrrdApply1DRegMap': (_equalsOne, 0, b'nrrd', 'nrrd/apply1D.c:514'),
    'nrrdApplyMulti1DRegMap': (_equalsOne, 0, b'nrrd', 'nrrd/apply1D.c:545'),
    'nrrd1DIrregMapCheck': (_equalsOne, 0, b'nrrd', 'nrrd/apply1D.c:587'),
    'nrrd1DIrregAclCheck': (_equalsOne, 0, b'nrrd', 'nrrd/apply1D.c:684'),
    'nrrd1DIrregAclGenerate': (_equalsOne, 0, b'nrrd', 'nrrd/apply1D.c:816'),
    'nrrdApply1DIrregMap': (_equalsOne, 0, b'nrrd', 'nrrd/apply1D.c:881'),
    'nrrdApply1DSubstitution': (_equalsOne, 0, b'nrrd', 'nrrd/apply1D.c:1055'),
    'nrrdApply2DLut': (_equalsOne, 0, b'nrrd', 'nrrd/apply2D.c:298'),
    'nrrdArithGamma': (_equalsOne, 0, b'nrrd', 'nrrd/arith.c:51'),
    'nrrdArithSRGBGamma': (_equalsOne, 0, b'nrrd', 'nrrd/arith.c:139'),
    'nrrdArithUnaryOp': (_equalsOne, 0, b'nrrd', 'nrrd/arith.c:345'),
    'nrrdArithBinaryOp': (_equalsOne, 0, b'nrrd', 'nrrd/arith.c:554'),
    'nrrdArithIterBinaryOpSelect': (_equalsOne, 0, b'nrrd', 'nrrd/arith.c:640'),
    'nrrdArithIterBinaryOp': (_equalsOne, 0, b'nrrd', 'nrrd/arith.c:727'),
    'nrrdArithTernaryOp': (_equalsOne, 0, b'nrrd', 'nrrd/arith.c:877'),
    'nrrdArithIterTernaryOpSelect': (_equalsOne, 0, b'nrrd', 'nrrd/arith.c:955'),
    'nrrdArithIterTernaryOp': (_equalsOne, 0, b'nrrd', 'nrrd/arith.c:1043'),
    'nrrdArithAffine': (_equalsOne, 0, b'nrrd', 'nrrd/arith.c:1066'),
    'nrrdArithIterAffine': (_equalsOne, 0, b'nrrd', 'nrrd/arith.c:1109'),
    'nrrdAxisInfoCompare': (_equalsOne, 0, b'nrrd', 'nrrd/axis.c:930'),
    'nrrdOrientationReduce': (_equalsOne, 0, b'nrrd', 'nrrd/axis.c:1222'),
    'nrrdMetaDataNormalize': (_equalsOne, 0, b'nrrd', 'nrrd/axis.c:1267'),
    'nrrdCCFind': (_equalsOne, 0, b'nrrd', 'nrrd/cc.c:286'),
    'nrrdCCAdjacency': (_equalsOne, 0, b'nrrd', 'nrrd/cc.c:543'),
    'nrrdCCMerge': (_equalsOne, 0, b'nrrd', 'nrrd/cc.c:643'),
    'nrrdCCRevalue': (_equalsOne, 0, b'nrrd', 'nrrd/cc.c:793'),
    'nrrdCCSettle': (_equalsOne, 0, b'nrrd', 'nrrd/cc.c:820'),
    'nrrdCCValid': ((lambda rv: 0 == rv), 0, b'nrrd', 'nrrd/ccmethods.c:27'),
    'nrrdCCSize': (_equalsOne, 0, b'nrrd', 'nrrd/ccmethods.c:58'),
    'nrrdDeringVerboseSet': (_equalsOne, 0, b'nrrd', 'nrrd/deringNrrd.c:102'),
    'nrrdDeringLinearInterpSet': (_equalsOne, 0, b'nrrd', 'nrrd/deringNrrd.c:115'),
    'nrrdDeringVerticalSeamSet': (_equalsOne, 0, b'nrrd', 'nrrd/deringNrrd.c:128'),
    'nrrdDeringInputSet': (_equalsOne, 0, b'nrrd', 'nrrd/deringNrrd.c:141'),
    'nrrdDeringCenterSet': (_equalsOne, 0, b'nrrd', 'nrrd/deringNrrd.c:176'),
    'nrrdDeringClampPercSet': (_equalsOne, 0, b'nrrd', 'nrrd/deringNrrd.c:195'),
    'nrrdDeringClampHistoBinsSet': (_equalsOne, 0, b'nrrd', 'nrrd/deringNrrd.c:216'),
    'nrrdDeringRadiusScaleSet': (_equalsOne, 0, b'nrrd', 'nrrd/deringNrrd.c:235'),
    'nrrdDeringThetaNumSet': (_equalsOne, 0, b'nrrd', 'nrrd/deringNrrd.c:253'),
    'nrrdDeringRadialKernelSet': (_equalsOne, 0, b'nrrd', 'nrrd/deringNrrd.c:271'),
    'nrrdDeringThetaKernelSet': (_equalsOne, 0, b'nrrd', 'nrrd/deringNrrd.c:291'),
    'nrrdDeringExecute': (_equalsOne, 0, b'nrrd', 'nrrd/deringNrrd.c:752'),
    'nrrdCheapMedian': (_equalsOne, 0, b'nrrd', 'nrrd/filt.c:408'),
    'nrrdDistanceL2': (_equalsOne, 0, b'nrrd', 'nrrd/filt.c:815'),
    'nrrdDistanceL2Biased': (_equalsOne, 0, b'nrrd', 'nrrd/filt.c:827'),
    'nrrdDistanceL2Signed': (_equalsOne, 0, b'nrrd', 'nrrd/filt.c:839'),
    'nrrdHisto': (_equalsOne, 0, b'nrrd', 'nrrd/histogram.c:41'),
    'nrrdHistoCheck': (_equalsOne, 0, b'nrrd', 'nrrd/histogram.c:161'),
    'nrrdHistoDraw': (_equalsOne, 0, b'nrrd', 'nrrd/histogram.c:190'),
    'nrrdHistoAxis': (_equalsOne, 0, b'nrrd', 'nrrd/histogram.c:326'),
    'nrrdHistoJoint': (_equalsOne, 0, b'nrrd', 'nrrd/histogram.c:440'),
    'nrrdHistoThresholdOtsu': (_equalsOne, 0, b'nrrd', 'nrrd/histogram.c:651'),
    'nrrdKernelParse': (_equalsOne, 0, b'nrrd', 'nrrd/kernel.c:2972'),
    'nrrdKernelSpecParse': (_equalsOne, 0, b'nrrd', 'nrrd/kernel.c:3152'),
    'nrrdKernelSpecSprint': (_equalsOne, 0, b'nrrd', 'nrrd/kernel.c:3174'),
    'nrrdKernelSprint': (_equalsOne, 0, b'nrrd', 'nrrd/kernel.c:3229'),
    'nrrdKernelCompare': (_equalsOne, 0, b'nrrd', 'nrrd/kernel.c:3247'),
    'nrrdKernelSpecCompare': (_equalsOne, 0, b'nrrd', 'nrrd/kernel.c:3296'),
    'nrrdKernelCheck': (_equalsOne, 0, b'nrrd', 'nrrd/kernel.c:3365'),
    'nrrdConvert': (_equalsOne, 0, b'nrrd', 'nrrd/map.c:235'),
    'nrrdClampConvert': (_equalsOne, 0, b'nrrd', 'nrrd/map.c:255'),
    'nrrdCastClampRound': (_equalsOne, 0, b'nrrd', 'nrrd/map.c:281'),
    'nrrdQuantize': (_equalsOne, 0, b'nrrd', 'nrrd/map.c:303'),
    'nrrdUnquantize': (_equalsOne, 0, b'nrrd', 'nrrd/map.c:475'),
    'nrrdHistoEq': (_equalsOne, 0, b'nrrd', 'nrrd/map.c:612'),
    'nrrdProject': (_equalsOne, 0, b'nrrd', 'nrrd/measure.c:1131'),
    'nrrdBoundarySpecCheck': (_equalsOne, 0, b'nrrd', 'nrrd/methodsNrrd.c:94'),
    'nrrdBoundarySpecParse': (_equalsOne, 0, b'nrrd', 'nrrd/methodsNrrd.c:118'),
    'nrrdBoundarySpecSprint': (_equalsOne, 0, b'nrrd', 'nrrd/methodsNrrd.c:177'),
    'nrrdBoundarySpecCompare': (_equalsOne, 0, b'nrrd', 'nrrd/methodsNrrd.c:199'),
    'nrrdBasicInfoCopy': (_equalsOne, 0, b'nrrd', 'nrrd/methodsNrrd.c:539'),
    'nrrdWrap_nva': (_equalsOne, 0, b'nrrd', 'nrrd/methodsNrrd.c:815'),
    'nrrdWrap_va': (_equalsOne, 0, b'nrrd', 'nrrd/methodsNrrd.c:846'),
    'nrrdCopy': (_equalsOne, 0, b'nrrd', 'nrrd/methodsNrrd.c:937'),
    'nrrdAlloc_nva': (_equalsOne, 0, b'nrrd', 'nrrd/methodsNrrd.c:967'),
    'nrrdAlloc_va': (_equalsOne, 0, b'nrrd', 'nrrd/methodsNrrd.c:1016'),
    'nrrdMaybeAlloc_nva': (_equalsOne, 0, b'nrrd', 'nrrd/methodsNrrd.c:1137'),
    'nrrdMaybeAlloc_va': (_equalsOne, 0, b'nrrd', 'nrrd/methodsNrrd.c:1154'),
    'nrrdCompare': (_equalsOne, 0, b'nrrd', 'nrrd/methodsNrrd.c:1195'),
    'nrrdPPM': (_equalsOne, 0, b'nrrd', 'nrrd/methodsNrrd.c:1381'),
    'nrrdPGM': (_equalsOne, 0, b'nrrd', 'nrrd/methodsNrrd.c:1401'),
    'nrrdSpaceVectorParse': (_equalsOne, 4, b'nrrd', 'nrrd/parseNrrd.c:522'),
    '_nrrdDataFNCheck': (_equalsOne, 3, b'nrrd', 'nrrd/parseNrrd.c:1199'),
    'nrrdRangePercentileSet': (_equalsOne, 0, b'nrrd', 'nrrd/range.c:110'),
    'nrrdRangePercentileFromStringSet': (_equalsOne, 0, b'nrrd', 'nrrd/range.c:212'),
    'nrrdOneLine': (_equalsOne, 0, b'nrrd', 'nrrd/read.c:73'),
    'nrrdLineSkip': (_equalsOne, 0, b'nrrd', 'nrrd/read.c:237'),
    'nrrdByteSkip': (_equalsOne, 0, b'nrrd', 'nrrd/read.c:333'),
    'nrrdRead': (_equalsOne, 0, b'nrrd', 'nrrd/read.c:497'),
    'nrrdStringRead': (_equalsOne, 0, b'nrrd', 'nrrd/read.c:517'),
    'nrrdLoad': ((lambda rv: 1 == rv or 2 == rv), 0, b'nrrd', 'nrrd/read.c:613'),
    'nrrdLoadMulti': (_equalsOne, 0, b'nrrd', 'nrrd/read.c:667'),
    'nrrdInvertPerm': (_equalsOne, 0, b'nrrd', 'nrrd/reorder.c:35'),
    'nrrdAxesInsert': (_equalsOne, 0, b'nrrd', 'nrrd/reorder.c:87'),
    'nrrdAxesPermute': (_equalsOne, 0, b'nrrd', 'nrrd/reorder.c:153'),
    'nrrdShuffle': (_equalsOne, 0, b'nrrd', 'nrrd/reorder.c:307'),
    'nrrdAxesSwap': (_equalsOne, 0, b'nrrd', 'nrrd/reorder.c:452'),
    'nrrdFlip': (_equalsOne, 0, b'nrrd', 'nrrd/reorder.c:488'),
    'nrrdJoin': (_equalsOne, 0, b'nrrd', 'nrrd/reorder.c:569'),
    'nrrdAxesSplit': (_equalsOne, 0, b'nrrd', 'nrrd/reorder.c:819'),
    'nrrdAxesDelete': (_equalsOne, 0, b'nrrd', 'nrrd/reorder.c:881'),
    'nrrdAxesMerge': (_equalsOne, 0, b'nrrd', 'nrrd/reorder.c:933'),
    'nrrdReshape_nva': (_equalsOne, 0, b'nrrd', 'nrrd/reorder.c:983'),
    'nrrdReshape_va': (_equalsOne, 0, b'nrrd', 'nrrd/reorder.c:1051'),
    'nrrdBlock': (_equalsOne, 0, b'nrrd', 'nrrd/reorder.c:1088'),
    'nrrdUnblock': (_equalsOne, 0, b'nrrd', 'nrrd/reorder.c:1159'),
    'nrrdTile2D': (_equalsOne, 0, b'nrrd', 'nrrd/reorder.c:1258'),
    'nrrdUntile2D': (_equalsOne, 0, b'nrrd', 'nrrd/reorder.c:1372'),
    'nrrdResampleDefaultCenterSet': (_equalsOne, 0, b'nrrd', 'nrrd/resampleContext.c:171'),
    'nrrdResampleNonExistentSet': (_equalsOne, 0, b'nrrd', 'nrrd/resampleContext.c:192'),
    'nrrdResampleRangeSet': (_equalsOne, 0, b'nrrd', 'nrrd/resampleContext.c:325'),
    'nrrdResampleOverrideCenterSet': (_equalsOne, 0, b'nrrd', 'nrrd/resampleContext.c:344'),
    'nrrdResampleBoundarySet': (_equalsOne, 0, b'nrrd', 'nrrd/resampleContext.c:401'),
    'nrrdResamplePadValueSet': (_equalsOne, 0, b'nrrd', 'nrrd/resampleContext.c:422'),
    'nrrdResampleBoundarySpecSet': (_equalsOne, 0, b'nrrd', 'nrrd/resampleContext.c:439'),
    'nrrdResampleRenormalizeSet': (_equalsOne, 0, b'nrrd', 'nrrd/resampleContext.c:460'),
    'nrrdResampleTypeOutSet': (_equalsOne, 0, b'nrrd', 'nrrd/resampleContext.c:477'),
    'nrrdResampleRoundSet': (_equalsOne, 0, b'nrrd', 'nrrd/resampleContext.c:502'),
    'nrrdResampleClampSet': (_equalsOne, 0, b'nrrd', 'nrrd/resampleContext.c:519'),
    'nrrdResampleExecute': (_equalsOne, 0, b'nrrd', 'nrrd/resampleContext.c:1457'),
    'nrrdFFTWWisdomRead': (_equalsOne, 0, b'nrrd', 'nrrd/fftNrrd.c:35'),
    'nrrdFFT': (_equalsOne, 0, b'nrrd', 'nrrd/fftNrrd.c:91'),
    'nrrdFFTWWisdomWrite': (_equalsOne, 0, b'nrrd', 'nrrd/fftNrrd.c:288'),
    'nrrdSimpleResample': (_equalsOne, 0, b'nrrd', 'nrrd/resampleNrrd.c:52'),
    'nrrdSpatialResample': (_equalsOne, 0, b'nrrd', 'nrrd/resampleNrrd.c:522'),
    'nrrdSpaceSet': (_equalsOne, 0, b'nrrd', 'nrrd/simple.c:86'),
    'nrrdSpaceDimensionSet': (_equalsOne, 0, b'nrrd', 'nrrd/simple.c:123'),
    'nrrdSpaceOriginSet': (_equalsOne, 0, b'nrrd', 'nrrd/simple.c:175'),
    'nrrdContentSet_va': (_equalsOne, 0, b'nrrd', 'nrrd/simple.c:476'),
    '_nrrdCheck': (_equalsOne, 3, b'nrrd', 'nrrd/simple.c:1080'),
    'nrrdCheck': (_equalsOne, 0, b'nrrd', 'nrrd/simple.c:1117'),
    'nrrdSameSize': ((lambda rv: 0 == rv), 3, b'nrrd', 'nrrd/simple.c:1138'),
    'nrrdSanity': ((lambda rv: 0 == rv), 0, b'nrrd', 'nrrd/simple.c:1370'),
    'nrrdSlice': (_equalsOne, 0, b'nrrd', 'nrrd/subset.c:40'),
    'nrrdCrop': (_equalsOne, 0, b'nrrd', 'nrrd/subset.c:185'),
    'nrrdSliceSelect': (_equalsOne, 0, b'nrrd', 'nrrd/subset.c:367'),
    'nrrdSample_nva': (_equalsOne, 0, b'nrrd', 'nrrd/subset.c:579'),
    'nrrdSample_va': (_equalsOne, 0, b'nrrd', 'nrrd/subset.c:618'),
    'nrrdSimpleCrop': (_equalsOne, 0, b'nrrd', 'nrrd/subset.c:647'),
    'nrrdCropAuto': (_equalsOne, 0, b'nrrd', 'nrrd/subset.c:668'),
    'nrrdSplice': (_equalsOne, 0, b'nrrd', 'nrrd/superset.c:33'),
    'nrrdInset': (_equalsOne, 0, b'nrrd', 'nrrd/superset.c:158'),
    'nrrdPad_va': (_equalsOne, 0, b'nrrd', 'nrrd/superset.c:282'),
    'nrrdPad_nva': (_equalsOne, 0, b'nrrd', 'nrrd/superset.c:488'),
    'nrrdSimplePad_va': (_equalsOne, 0, b'nrrd', 'nrrd/superset.c:516'),
    'nrrdSimplePad_nva': (_equalsOne, 0, b'nrrd', 'nrrd/superset.c:554'),
    'nrrdIoStateSet': (_equalsOne, 0, b'nrrd', 'nrrd/write.c:32'),
    'nrrdIoStateEncodingSet': (_equalsOne, 0, b'nrrd', 'nrrd/write.c:105'),
    'nrrdIoStateFormatSet': (_equalsOne, 0, b'nrrd', 'nrrd/write.c:125'),
    'nrrdWrite': (_equalsOne, 0, b'nrrd', 'nrrd/write.c:945'),
    'nrrdStringWrite': (_equalsOne, 0, b'nrrd', 'nrrd/write.c:961'),
    'nrrdSave': (_equalsOne, 0, b'nrrd', 'nrrd/write.c:982'),
    'nrrdSaveMulti': (_equalsOne, 0, b'nrrd', 'nrrd/write.c:1035'),
    'ell_Nm_check': (_equalsOne, 0, b'ell', 'ell/genmat.c:26'),
    'ell_Nm_tran': (_equalsOne, 0, b'ell', 'ell/genmat.c:60'),
    'ell_Nm_mul': (_equalsOne, 0, b'ell', 'ell/genmat.c:105'),
    'ell_Nm_inv': (_equalsOne, 0, b'ell', 'ell/genmat.c:339'),
    'ell_Nm_pseudo_inv': (_equalsOne, 0, b'ell', 'ell/genmat.c:380'),
    'ell_Nm_wght_pseudo_inv': (_equalsOne, 0, b'ell', 'ell/genmat.c:414'),
    'ell_q_avg4_d': (_equalsOne, 0, b'ell', 'ell/quat.c:472'),
    'ell_q_avgN_d': (_equalsOne, 0, b'ell', 'ell/quat.c:540'),
    'mossImageCheck': (_equalsOne, 0, b'moss', 'moss/methodsMoss.c:74'),
    'mossImageAlloc': (_equalsOne, 0, b'moss', 'moss/methodsMoss.c:95'),
    'mossSamplerImageSet': (_equalsOne, 0, b'moss', 'moss/sampler.c:27'),
    'mossSamplerKernelSet': (_equalsOne, 0, b'moss', 'moss/sampler.c:79'),
    'mossSamplerUpdate': (_equalsOne, 0, b'moss', 'moss/sampler.c:101'),
    'mossSamplerSample': (_equalsOne, 0, b'moss', 'moss/sampler.c:196'),
    'mossLinearTransform': (_equalsOne, 0, b'moss', 'moss/xform.c:141'),
    'mossFourPointTransform': (_equalsOne, 0, b'moss', 'moss/xform.c:220'),
    'alanUpdate': (_equalsOne, 0, b'alan', 'alan/coreAlan.c:61'),
    'alanInit': (_equalsOne, 0, b'alan', 'alan/coreAlan.c:104'),
    'alanRun': (_equalsOne, 0, b'alan', 'alan/coreAlan.c:457'),
    'alanDimensionSet': (_equalsOne, 0, b'alan', 'alan/methodsAlan.c:105'),
    'alan2DSizeSet': (_equalsOne, 0, b'alan', 'alan/methodsAlan.c:120'),
    'alan3DSizeSet': (_equalsOne, 0, b'alan', 'alan/methodsAlan.c:140'),
    'alanTensorSet': (_equalsOne, 0, b'alan', 'alan/methodsAlan.c:161'),
    'alanParmSet': (_equalsOne, 0, b'alan', 'alan/methodsAlan.c:208'),
    'gageContextCopy': ((lambda rv: _teem.ffi.NULL == rv), 0, b'gage', 'gage/ctx.c:89'),
    'gageKernelSet': (_equalsOne, 0, b'gage', 'gage/ctx.c:200'),
    'gagePerVolumeAttach': (_equalsOne, 0, b'gage', 'gage/ctx.c:399'),
    'gagePerVolumeDetach': (_equalsOne, 0, b'gage', 'gage/ctx.c:458'),
    'gageDeconvolve': (_equalsOne, 0, b'gage', 'gage/deconvolve.c:27'),
    'gageDeconvolveSeparable': (_equalsOne, 0, b'gage', 'gage/deconvolve.c:209'),
    'gageKindCheck': (_equalsOne, 0, b'gage', 'gage/kind.c:34'),
    'gageKindVolumeCheck': (_equalsOne, 0, b'gage', 'gage/kind.c:219'),
    'gageVolumeCheck': (_equalsOne, 0, b'gage', 'gage/pvl.c:37'),
    'gagePerVolumeNew': ((lambda rv: _teem.ffi.NULL == rv), 0, b'gage', 'gage/pvl.c:58'),
    'gageQueryReset': (_equalsOne, 0, b'gage', 'gage/pvl.c:262'),
    'gageQuerySet': (_equalsOne, 0, b'gage', 'gage/pvl.c:288'),
    'gageQueryAdd': (_equalsOne, 0, b'gage', 'gage/pvl.c:344'),
    'gageQueryItemOn': (_equalsOne, 0, b'gage', 'gage/pvl.c:362'),
    'gageShapeSet': (_equalsOne, 0, b'gage', 'gage/shape.c:406'),
    'gageShapeEqual': ((lambda rv: 0 == rv), 0, b'gage', 'gage/shape.c:469'),
    'gageStructureTensor': (_equalsOne, 0, b'gage', 'gage/st.c:84'),
    'gageStackPerVolumeNew': (_equalsOne, 0, b'gage', 'gage/stack.c:99'),
    'gageStackPerVolumeAttach': (_equalsOne, 0, b'gage', 'gage/stack.c:128'),
    'gageStackBlurParmCompare': (_equalsOne, 0, b'gage', 'gage/stackBlur.c:126'),
    'gageStackBlurParmCopy': (_equalsOne, 0, b'gage', 'gage/stackBlur.c:231'),
    'gageStackBlurParmSigmaSet': (_equalsOne, 0, b'gage', 'gage/stackBlur.c:268'),
    'gageStackBlurParmScaleSet': (_equalsOne, 0, b'gage', 'gage/stackBlur.c:362'),
    'gageStackBlurParmKernelSet': (_equalsOne, 0, b'gage', 'gage/stackBlur.c:386'),
    'gageStackBlurParmRenormalizeSet': (_equalsOne, 0, b'gage', 'gage/stackBlur.c:399'),
    'gageStackBlurParmBoundarySet': (_equalsOne, 0, b'gage', 'gage/stackBlur.c:411'),
    'gageStackBlurParmBoundarySpecSet': (_equalsOne, 0, b'gage', 'gage/stackBlur.c:430'),
    'gageStackBlurParmOneDimSet': (_equalsOne, 0, b'gage', 'gage/stackBlur.c:447'),
    'gageStackBlurParmNeedSpatialBlurSet': (_equalsOne, 0, b'gage', 'gage/stackBlur.c:459'),
    'gageStackBlurParmVerboseSet': (_equalsOne, 0, b'gage', 'gage/stackBlur.c:471'),
    'gageStackBlurParmDgGoodSigmaMaxSet': (_equalsOne, 0, b'gage', 'gage/stackBlur.c:483'),
    'gageStackBlurParmCheck': (_equalsOne, 0, b'gage', 'gage/stackBlur.c:499'),
    'gageStackBlurParmParse': (_equalsOne, 0, b'gage', 'gage/stackBlur.c:546'),
    'gageStackBlurParmSprint': (_equalsOne, 0, b'gage', 'gage/stackBlur.c:805'),
    'gageStackBlur': (_equalsOne, 0, b'gage', 'gage/stackBlur.c:1387'),
    'gageStackBlurCheck': (_equalsOne, 0, b'gage', 'gage/stackBlur.c:1490'),
    'gageStackBlurGet': (_equalsOne, 0, b'gage', 'gage/stackBlur.c:1598'),
    'gageStackBlurManage': (_equalsOne, 0, b'gage', 'gage/stackBlur.c:1699'),
    'gageUpdate': (_equalsOne, 0, b'gage', 'gage/update.c:314'),
    'gageOptimSigSet': (_equalsOne, 0, b'gage', 'gage/optimsig.c:218'),
    'gageOptimSigContextNew': ((lambda rv: _teem.ffi.NULL == rv), 0, b'gage', 'gage/optimsig.c:312'),
    'gageOptimSigCalculate': (_equalsOne, 0, b'gage', 'gage/optimsig.c:1093'),
    'gageOptimSigErrorPlot': (_equalsOne, 0, b'gage', 'gage/optimsig.c:1165'),
    'gageOptimSigErrorPlotSliding': (_equalsOne, 0, b'gage', 'gage/optimsig.c:1256'),
    'dyeConvert': (_equalsOne, 0, b'dye', 'dye/convertDye.c:352'),
    'dyeColorParse': (_equalsOne, 0, b'dye', 'dye/methodsDye.c:186'),
    'baneClipNew': ((lambda rv: _teem.ffi.NULL == rv), 0, b'bane', 'bane/clip.c:103'),
    'baneClipAnswer': (_equalsOne, 0, b'bane', 'bane/clip.c:153'),
    'baneClipCopy': ((lambda rv: _teem.ffi.NULL == rv), 0, b'bane', 'bane/clip.c:168'),
    'baneFindInclusion': (_equalsOne, 0, b'bane', 'bane/hvol.c:88'),
    'baneMakeHVol': (_equalsOne, 0, b'bane', 'bane/hvol.c:250'),
    'baneGKMSHVol': ((lambda rv: _teem.ffi.NULL == rv), 0, b'bane', 'bane/hvol.c:449'),
    'baneIncNew': ((lambda rv: _teem.ffi.NULL == rv), 0, b'bane', 'bane/inc.c:252'),
    'baneIncAnswer': (_equalsOne, 0, b'bane', 'bane/inc.c:361'),
    'baneIncCopy': ((lambda rv: _teem.ffi.NULL == rv), 0, b'bane', 'bane/inc.c:376'),
    'baneMeasrNew': ((lambda rv: _teem.ffi.NULL == rv), 0, b'bane', 'bane/measr.c:34'),
    'baneMeasrCopy': ((lambda rv: _teem.ffi.NULL == rv), 0, b'bane', 'bane/measr.c:150'),
    'baneRangeNew': ((lambda rv: _teem.ffi.NULL == rv), 0, b'bane', 'bane/rangeBane.c:90'),
    'baneRangeCopy': ((lambda rv: _teem.ffi.NULL == rv), 0, b'bane', 'bane/rangeBane.c:131'),
    'baneRangeAnswer': (_equalsOne, 0, b'bane', 'bane/rangeBane.c:145'),
    'baneRawScatterplots': (_equalsOne, 0, b'bane', 'bane/scat.c:27'),
    'baneOpacInfo': (_equalsOne, 0, b'bane', 'bane/trnsf.c:30'),
    'bane1DOpacInfoFrom2D': (_equalsOne, 0, b'bane', 'bane/trnsf.c:146'),
    'baneSigmaCalc': (_equalsOne, 0, b'bane', 'bane/trnsf.c:225'),
    'banePosCalc': (_equalsOne, 0, b'bane', 'bane/trnsf.c:256'),
    'baneOpacCalc': (_equalsOne, 0, b'bane', 'bane/trnsf.c:407'),
    'baneInputCheck': (_equalsOne, 0, b'bane', 'bane/valid.c:27'),
    'baneHVolCheck': (_equalsOne, 0, b'bane', 'bane/valid.c:65'),
    'baneInfoCheck': (_equalsOne, 0, b'bane', 'bane/valid.c:107'),
    'banePosCheck': (_equalsOne, 0, b'bane', 'bane/valid.c:145'),
    'baneBcptsCheck': (_equalsOne, 0, b'bane', 'bane/valid.c:180'),
    'limnCameraUpdate': (_equalsOne, 0, b'limn', 'limn/cam.c:34'),
    'limnCameraAspectSet': (_equalsOne, 0, b'limn', 'limn/cam.c:131'),
    'limnCameraPathMake': (_equalsOne, 0, b'limn', 'limn/cam.c:190'),
    'limnEnvMapFill': (_equalsOne, 0, b'limn', 'limn/envmap.c:26'),
    'limnEnvMapCheck': (_equalsOne, 0, b'limn', 'limn/envmap.c:120'),
    'limnObjectWriteOFF': (_equalsOne, 0, b'limn', 'limn/io.c:80'),
    'limnPolyDataWriteIV': (_equalsOne, 0, b'limn', 'limn/io.c:139'),
    'limnObjectReadOFF': (_equalsOne, 0, b'limn', 'limn/io.c:265'),
    'limnPolyDataWriteLMPD': (_equalsOne, 0, b'limn', 'limn/io.c:456'),
    'limnPolyDataReadLMPD': (_equalsOne, 0, b'limn', 'limn/io.c:583'),
    'limnPolyDataWriteVTK': (_equalsOne, 0, b'limn', 'limn/io.c:966'),
    'limnPolyDataReadOFF': (_equalsOne, 0, b'limn', 'limn/io.c:1056'),
    'limnPolyDataSave': (_equalsOne, 0, b'limn', 'limn/io.c:1161'),
    'limnLightUpdate': (_equalsOne, 0, b'limn', 'limn/light.c:68'),
    'limnPolyDataAlloc': (_equalsOne, 0, b'limn', 'limn/polydata.c:150'),
    'limnPolyDataCopy': (_equalsOne, 0, b'limn', 'limn/polydata.c:229'),
    'limnPolyDataCopyN': (_equalsOne, 0, b'limn', 'limn/polydata.c:261'),
    'limnPolyDataPrimitiveVertexNumber': (_equalsOne, 0, b'limn', 'limn/polydata.c:552'),
    'limnPolyDataPrimitiveArea': (_equalsOne, 0, b'limn', 'limn/polydata.c:574'),
    'limnPolyDataRasterize': (_equalsOne, 0, b'limn', 'limn/polydata.c:632'),
    'limnPolyDataSpiralTubeWrap': (_equalsOne, 0, b'limn', 'limn/polyfilter.c:27'),
    'limnPolyDataSmoothHC': ((lambda rv: -1 == rv), 0, b'limn', 'limn/polyfilter.c:337'),
    'limnPolyDataVertexWindingFix': (_equalsOne, 0, b'limn', 'limn/polymod.c:1233'),
    'limnPolyDataCCFind': (_equalsOne, 0, b'limn', 'limn/polymod.c:1252'),
    'limnPolyDataPrimitiveSort': (_equalsOne, 0, b'limn', 'limn/polymod.c:1383'),
    'limnPolyDataVertexWindingFlip': (_equalsOne, 0, b'limn', 'limn/polymod.c:1466'),
    'limnPolyDataPrimitiveSelect': (_equalsOne, 0, b'limn', 'limn/polymod.c:1495'),
    'limnPolyDataClipMulti': (_equalsOne, 0, b'limn', 'limn/polymod.c:1710'),
    'limnPolyDataCompress': ((lambda rv: _teem.ffi.NULL == rv), 0, b'limn', 'limn/polymod.c:1997'),
    'limnPolyDataJoin': ((lambda rv: _teem.ffi.NULL == rv), 0, b'limn', 'limn/polymod.c:2087'),
    'limnPolyDataEdgeHalve': (_equalsOne, 0, b'limn', 'limn/polymod.c:2155'),
    'limnPolyDataNeighborList': ((lambda rv: -1 == rv), 0, b'limn', 'limn/polymod.c:2332'),
    'limnPolyDataNeighborArray': ((lambda rv: -1 == rv), 0, b'limn', 'limn/polymod.c:2428'),
    'limnPolyDataNeighborArrayComp': ((lambda rv: -1 == rv), 0, b'limn', 'limn/polymod.c:2468'),
    'limnPolyDataCube': (_equalsOne, 0, b'limn', 'limn/polyshapes.c:28'),
    'limnPolyDataCubeTriangles': (_equalsOne, 0, b'limn', 'limn/polyshapes.c:138'),
    'limnPolyDataOctahedron': (_equalsOne, 0, b'limn', 'limn/polyshapes.c:348'),
    'limnPolyDataCylinder': (_equalsOne, 0, b'limn', 'limn/polyshapes.c:462'),
    'limnPolyDataCone': (_equalsOne, 0, b'limn', 'limn/polyshapes.c:636'),
    'limnPolyDataSuperquadric': (_equalsOne, 0, b'limn', 'limn/polyshapes.c:735'),
    'limnPolyDataSpiralBetterquadric': (_equalsOne, 0, b'limn', 'limn/polyshapes.c:860'),
    'limnPolyDataSpiralSuperquadric': (_equalsOne, 0, b'limn', 'limn/polyshapes.c:1017'),
    'limnPolyDataPolarSphere': (_equalsOne, 0, b'limn', 'limn/polyshapes.c:1035'),
    'limnPolyDataSpiralSphere': (_equalsOne, 0, b'limn', 'limn/polyshapes.c:1047'),
    'limnPolyDataIcoSphere': (_equalsOne, 0, b'limn', 'limn/polyshapes.c:1098'),
    'limnPolyDataPlane': (_equalsOne, 0, b'limn', 'limn/polyshapes.c:1342'),
    'limnPolyDataSquare': (_equalsOne, 0, b'limn', 'limn/polyshapes.c:1397'),
    'limnPolyDataSuperquadric2D': (_equalsOne, 0, b'limn', 'limn/polyshapes.c:1440'),
    'limnQNDemo': (_equalsOne, 0, b'limn', 'limn/qn.c:893'),
    'limnObjectRender': (_equalsOne, 0, b'limn', 'limn/renderLimn.c:26'),
    'limnObjectPSDraw': (_equalsOne, 0, b'limn', 'limn/renderLimn.c:185'),
    'limnObjectPSDrawConcave': (_equalsOne, 0, b'limn', 'limn/renderLimn.c:315'),
    'limnSplineNrrdEvaluate': (_equalsOne, 0, b'limn', 'limn/splineEval.c:324'),
    'limnSplineSample': (_equalsOne, 0, b'limn', 'limn/splineEval.c:362'),
    'limnSplineTypeSpecNew': ((lambda rv: _teem.ffi.NULL == rv), 0, b'limn', 'limn/splineMethods.c:26'),
    'limnSplineNew': ((lambda rv: _teem.ffi.NULL == rv), 0, b'limn', 'limn/splineMethods.c:125'),
    'limnSplineNrrdCleverFix': (_equalsOne, 0, b'limn', 'limn/splineMethods.c:250'),
    'limnSplineCleverNew': ((lambda rv: _teem.ffi.NULL == rv), 0, b'limn', 'limn/splineMethods.c:395'),
    'limnSplineUpdate': (_equalsOne, 0, b'limn', 'limn/splineMethods.c:423'),
    'limnSplineTypeSpecParse': ((lambda rv: _teem.ffi.NULL == rv), 0, b'limn', 'limn/splineMisc.c:223'),
    'limnSplineParse': ((lambda rv: _teem.ffi.NULL == rv), 0, b'limn', 'limn/splineMisc.c:279'),
    'limnCBFCheck': (_equalsOne, 0, b'limn', 'limn/splineFit.c:588'),
    'limnCBFitSingle': (_equalsOne, 0, b'limn', 'limn/splineFit.c:859'),
    'limnCBFMulti': (_equalsOne, 0, b'limn', 'limn/splineFit.c:950'),
    'limnCBFCorners': (_equalsOne, 0, b'limn', 'limn/splineFit.c:1052'),
    'limnCBFit': (_equalsOne, 0, b'limn', 'limn/splineFit.c:1122'),
    'limnObjectWorldHomog': (_equalsOne, 0, b'limn', 'limn/transform.c:26'),
    'limnObjectFaceNormals': (_equalsOne, 0, b'limn', 'limn/transform.c:48'),
    'limnObjectSpaceTransform': (_equalsOne, 0, b'limn', 'limn/transform.c:211'),
    'limnObjectFaceReverse': (_equalsOne, 0, b'limn', 'limn/transform.c:336'),
    'echoThreadStateInit': (_equalsOne, 0, b'echo', 'echo/renderEcho.c:27'),
    'echoRTRenderCheck': (_equalsOne, 0, b'echo', 'echo/renderEcho.c:137'),
    'echoRTRender': (_equalsOne, 0, b'echo', 'echo/renderEcho.c:412'),
    'hooverContextCheck': (_equalsOne, 0, b'hoover', 'hoover/methodsHoover.c:54'),
    'hooverRender': ((lambda rv: _teem.lib.hooverErrInit == rv), 0, b'hoover', 'hoover/rays.c:360'),
    'seekExtract': (_equalsOne, 0, b'seek', 'seek/extract.c:925'),
    'seekDataSet': (_equalsOne, 0, b'seek', 'seek/setSeek.c:57'),
    'seekSamplesSet': (_equalsOne, 0, b'seek', 'seek/setSeek.c:117'),
    'seekTypeSet': (_equalsOne, 0, b'seek', 'seek/setSeek.c:150'),
    'seekLowerInsideSet': (_equalsOne, 0, b'seek', 'seek/setSeek.c:174'),
    'seekNormalsFindSet': (_equalsOne, 0, b'seek', 'seek/setSeek.c:194'),
    'seekStrengthUseSet': (_equalsOne, 0, b'seek', 'seek/setSeek.c:209'),
    'seekStrengthSet': (_equalsOne, 0, b'seek', 'seek/setSeek.c:224'),
    'seekItemScalarSet': (_equalsOne, 0, b'seek', 'seek/setSeek.c:286'),
    'seekItemStrengthSet': (_equalsOne, 0, b'seek', 'seek/setSeek.c:305'),
    'seekItemHessSet': (_equalsOne, 0, b'seek', 'seek/setSeek.c:324'),
    'seekItemGradientSet': (_equalsOne, 0, b'seek', 'seek/setSeek.c:344'),
    'seekItemNormalSet': (_equalsOne, 0, b'seek', 'seek/setSeek.c:365'),
    'seekItemEigensystemSet': (_equalsOne, 0, b'seek', 'seek/setSeek.c:386'),
    'seekIsovalueSet': (_equalsOne, 0, b'seek', 'seek/setSeek.c:415'),
    'seekEvalDiffThreshSet': (_equalsOne, 0, b'seek', 'seek/setSeek.c:441'),
    'seekVertexStrength': (_equalsOne, 0, b'seek', 'seek/textract.c:1885'),
    'seekUpdate': (_equalsOne, 0, b'seek', 'seek/updateSeek.c:676'),
    'tenAnisoPlot': (_equalsOne, 0, b'ten', 'ten/aniso.c:1069'),
    'tenAnisoVolume': (_equalsOne, 0, b'ten', 'ten/aniso.c:1129'),
    'tenAnisoHistogram': (_equalsOne, 0, b'ten', 'ten/aniso.c:1201'),
    'tenEvecRGBParmCheck': (_equalsOne, 0, b'ten', 'ten/aniso.c:1316'),
    'tenEMBimodal': (_equalsOne, 0, b'ten', 'ten/bimod.c:413'),
    'tenBVecNonLinearFit': (_equalsOne, 0, b'ten', 'ten/bvec.c:100'),
    'tenDWMRIKeyValueParse': (_equalsOne, 0, b'ten', 'ten/chan.c:61'),
    'tenBMatrixCalc': (_equalsOne, 0, b'ten', 'ten/chan.c:349'),
    'tenEMatrixCalc': (_equalsOne, 0, b'ten', 'ten/chan.c:390'),
    'tenEstimateLinear3D': (_equalsOne, 0, b'ten', 'ten/chan.c:583'),
    'tenEstimateLinear4D': (_equalsOne, 0, b'ten', 'ten/chan.c:630'),
    'tenSimulate': (_equalsOne, 0, b'ten', 'ten/chan.c:871'),
    'tenEpiRegister3D': (_equalsOne, 0, b'ten', 'ten/epireg.c:1050'),
    'tenEpiRegister4D': (_equalsOne, 0, b'ten', 'ten/epireg.c:1201'),
    'tenEstimateMethodSet': (_equalsOne, 0, b'ten', 'ten/estimate.c:284'),
    'tenEstimateSigmaSet': (_equalsOne, 0, b'ten', 'ten/estimate.c:306'),
    'tenEstimateValueMinSet': (_equalsOne, 0, b'ten', 'ten/estimate.c:324'),
    'tenEstimateGradientsSet': (_equalsOne, 0, b'ten', 'ten/estimate.c:342'),
    'tenEstimateBMatricesSet': (_equalsOne, 0, b'ten', 'ten/estimate.c:369'),
    'tenEstimateSkipSet': (_equalsOne, 0, b'ten', 'ten/estimate.c:396'),
    'tenEstimateSkipReset': (_equalsOne, 0, b'ten', 'ten/estimate.c:414'),
    'tenEstimateThresholdFind': (_equalsOne, 0, b'ten', 'ten/estimate.c:429'),
    'tenEstimateThresholdSet': (_equalsOne, 0, b'ten', 'ten/estimate.c:497'),
    'tenEstimateUpdate': (_equalsOne, 0, b'ten', 'ten/estimate.c:805'),
    'tenEstimate1TensorSimulateSingle_f': (_equalsOne, 0, b'ten', 'ten/estimate.c:979'),
    'tenEstimate1TensorSimulateSingle_d': (_equalsOne, 0, b'ten', 'ten/estimate.c:1007'),
    'tenEstimate1TensorSimulateVolume': (_equalsOne, 0, b'ten', 'ten/estimate.c:1038'),
    'tenEstimate1TensorSingle_f': (_equalsOne, 0, b'ten', 'ten/estimate.c:1743'),
    'tenEstimate1TensorSingle_d': (_equalsOne, 0, b'ten', 'ten/estimate.c:1771'),
    'tenEstimate1TensorVolume4D': (_equalsOne, 0, b'ten', 'ten/estimate.c:1808'),
    'tenFiberTraceSet': (_equalsOne, 0, b'ten', 'ten/fiber.c:829'),
    'tenFiberTrace': (_equalsOne, 0, b'ten', 'ten/fiber.c:849'),
    'tenFiberDirectionNumber': ((lambda rv: 0 == rv), 0, b'ten', 'ten/fiber.c:869'),
    'tenFiberSingleTrace': (_equalsOne, 0, b'ten', 'ten/fiber.c:918'),
    'tenFiberMultiNew': ((lambda rv: _teem.ffi.NULL == rv), 0, b'ten', 'ten/fiber.c:961'),
    'tenFiberMultiTrace': (_equalsOne, 0, b'ten', 'ten/fiber.c:1026'),
    'tenFiberMultiPolyData': (_equalsOne, 0, b'ten', 'ten/fiber.c:1246'),
    'tenFiberMultiProbeVals': (_equalsOne, 0, b'ten', 'ten/fiber.c:1257'),
    'tenFiberContextDwiNew': ((lambda rv: _teem.ffi.NULL == rv), 0, b'ten', 'ten/fiberMethods.c:211'),
    'tenFiberContextNew': ((lambda rv: _teem.ffi.NULL == rv), 0, b'ten', 'ten/fiberMethods.c:225'),
    'tenFiberTypeSet': (_equalsOne, 0, b'ten', 'ten/fiberMethods.c:249'),
    'tenFiberStopSet': (_equalsOne, 0, b'ten', 'ten/fiberMethods.c:379'),
    'tenFiberStopAnisoSet': (_equalsOne, 0, b'ten', 'ten/fiberMethods.c:555'),
    'tenFiberStopDoubleSet': (_equalsOne, 0, b'ten', 'ten/fiberMethods.c:567'),
    'tenFiberStopUIntSet': (_equalsOne, 0, b'ten', 'ten/fiberMethods.c:591'),
    'tenFiberAnisoSpeedSet': (_equalsOne, 0, b'ten', 'ten/fiberMethods.c:638'),
    'tenFiberAnisoSpeedReset': (_equalsOne, 0, b'ten', 'ten/fiberMethods.c:703'),
    'tenFiberKernelSet': (_equalsOne, 0, b'ten', 'ten/fiberMethods.c:718'),
    'tenFiberProbeItemSet': (_equalsOne, 0, b'ten', 'ten/fiberMethods.c:737'),
    'tenFiberIntgSet': (_equalsOne, 0, b'ten', 'ten/fiberMethods.c:749'),
    'tenFiberUpdate': (_equalsOne, 0, b'ten', 'ten/fiberMethods.c:792'),
    'tenGlyphParmCheck': (_equalsOne, 0, b'ten', 'ten/glyph.c:73'),
    'tenGlyphGen': (_equalsOne, 0, b'ten', 'ten/glyph.c:174'),
    'tenGradientCheck': (_equalsOne, 0, b'ten', 'ten/grads.c:68'),
    'tenGradientRandom': (_equalsOne, 0, b'ten', 'ten/grads.c:107'),
    'tenGradientJitter': (_equalsOne, 0, b'ten', 'ten/grads.c:153'),
    'tenGradientBalance': (_equalsOne, 0, b'ten', 'ten/grads.c:375'),
    'tenGradientDistribute': (_equalsOne, 0, b'ten', 'ten/grads.c:460'),
    'tenGradientGenerate': (_equalsOne, 0, b'ten', 'ten/grads.c:653'),
    'tenEvecRGB': (_equalsOne, 0, b'ten', 'ten/miscTen.c:27'),
    'tenEvqVolume': (_equalsOne, 0, b'ten', 'ten/miscTen.c:152'),
    'tenBMatrixCheck': (_equalsOne, 0, b'ten', 'ten/miscTen.c:213'),
    '_tenFindValley': (_equalsOne, 0, b'ten', 'ten/miscTen.c:257'),
    'tenSizeNormalize': (_equalsOne, 0, b'ten', 'ten/mod.c:222'),
    'tenSizeScale': (_equalsOne, 0, b'ten', 'ten/mod.c:238'),
    'tenAnisoScale': (_equalsOne, 0, b'ten', 'ten/mod.c:256'),
    'tenEigenvalueClamp': (_equalsOne, 0, b'ten', 'ten/mod.c:276'),
    'tenEigenvaluePower': (_equalsOne, 0, b'ten', 'ten/mod.c:295'),
    'tenEigenvalueAdd': (_equalsOne, 0, b'ten', 'ten/mod.c:313'),
    'tenEigenvalueMultiply': (_equalsOne, 0, b'ten', 'ten/mod.c:331'),
    'tenLog': (_equalsOne, 0, b'ten', 'ten/mod.c:349'),
    'tenExp': (_equalsOne, 0, b'ten', 'ten/mod.c:366'),
    'tenInterpParmBufferAlloc': (_equalsOne, 0, b'ten', 'ten/path.c:65'),
    'tenInterpParmCopy': ((lambda rv: _teem.ffi.NULL == rv), 0, b'ten', 'ten/path.c:124'),
    'tenInterpN_d': (_equalsOne, 0, b'ten', 'ten/path.c:306'),
    'tenInterpTwoDiscrete_d': (_equalsOne, 0, b'ten', 'ten/path.c:809'),
    'tenInterpMulti3D': (_equalsOne, 0, b'ten', 'ten/path.c:960'),
    'tenDwiGageKindSet': (_equalsOne, 0, b'ten', 'ten/tenDwiGage.c:1038'),
    'tenDwiGageKindCheck': (_equalsOne, 0, b'ten', 'ten/tenDwiGage.c:1178'),
    'tenTensorCheck': (_equalsOne, 4, b'ten', 'ten/tensor.c:55'),
    'tenMeasurementFrameReduce': (_equalsOne, 0, b'ten', 'ten/tensor.c:88'),
    'tenExpand2D': (_equalsOne, 0, b'ten', 'ten/tensor.c:158'),
    'tenExpand': (_equalsOne, 0, b'ten', 'ten/tensor.c:232'),
    'tenShrink': (_equalsOne, 0, b'ten', 'ten/tensor.c:288'),
    'tenMake': (_equalsOne, 0, b'ten', 'ten/tensor.c:530'),
    'tenSlice': (_equalsOne, 0, b'ten', 'ten/tensor.c:632'),
    'tenTripleCalc': (_equalsOne, 0, b'ten', 'ten/triple.c:416'),
    'tenTripleConvert': (_equalsOne, 0, b'ten', 'ten/triple.c:474'),
    'tenExperSpecGradSingleBValSet': (_equalsOne, 0, b'ten', 'ten/experSpec.c:64'),
    'tenExperSpecGradBValSet': (_equalsOne, 0, b'ten', 'ten/experSpec.c:105'),
    'tenExperSpecFromKeyValueSet': (_equalsOne, 0, b'ten', 'ten/experSpec.c:174'),
    'tenDWMRIKeyValueFromExperSpecSet': (_equalsOne, 0, b'ten', 'ten/experSpec.c:329'),
    'tenModelParse': (_equalsOne, 0, b'ten', 'ten/tenModel.c:64'),
    'tenModelFromAxisLearn': (_equalsOne, 0, b'ten', 'ten/tenModel.c:125'),
    'tenModelSimulate': (_equalsOne, 0, b'ten', 'ten/tenModel.c:163'),
    'tenModelSqeFit': (_equalsOne, 0, b'ten', 'ten/tenModel.c:411'),
    'tenModelConvert': (_equalsOne, 0, b'ten', 'ten/tenModel.c:686'),
    'pullEnergyPlot': (_equalsOne, 0, b'pull', 'pull/actionPull.c:233'),
    'pullBinProcess': (_equalsOne, 0, b'pull', 'pull/actionPull.c:1107'),
    'pullGammaLearn': (_equalsOne, 0, b'pull', 'pull/actionPull.c:1142'),
    'pullBinsPointAdd': (_equalsOne, 0, b'pull', 'pull/binningPull.c:184'),
    'pullBinsPointMaybeAdd': (_equalsOne, 0, b'pull', 'pull/binningPull.c:206'),
    'pullOutputGetFilter': (_equalsOne, 0, b'pull', 'pull/contextPull.c:382'),
    'pullOutputGet': (_equalsOne, 0, b'pull', 'pull/contextPull.c:578'),
    'pullPropGet': (_equalsOne, 0, b'pull', 'pull/contextPull.c:591'),
    'pullPositionHistoryNrrdGet': (_equalsOne, 0, b'pull', 'pull/contextPull.c:769'),
    'pullPositionHistoryPolydataGet': (_equalsOne, 0, b'pull', 'pull/contextPull.c:841'),
    'pullIterParmSet': (_equalsOne, 0, b'pull', 'pull/parmPull.c:105'),
    'pullSysParmSet': (_equalsOne, 0, b'pull', 'pull/parmPull.c:194'),
    'pullFlagSet': (_equalsOne, 0, b'pull', 'pull/parmPull.c:273'),
    'pullVerboseSet': (_equalsOne, 0, b'pull', 'pull/parmPull.c:348'),
    'pullThreadNumSet': (_equalsOne, 0, b'pull', 'pull/parmPull.c:373'),
    'pullRngSeedSet': (_equalsOne, 0, b'pull', 'pull/parmPull.c:385'),
    'pullProgressBinModSet': (_equalsOne, 0, b'pull', 'pull/parmPull.c:397'),
    'pullCallbackSet': (_equalsOne, 0, b'pull', 'pull/parmPull.c:409'),
    'pullInterEnergySet': (_equalsOne, 0, b'pull', 'pull/parmPull.c:434'),
    'pullLogAddSet': (_equalsOne, 0, b'pull', 'pull/parmPull.c:495'),
    'pullInitRandomSet': (_equalsOne, 0, b'pull', 'pull/initPull.c:110'),
    'pullInitHaltonSet': (_equalsOne, 0, b'pull', 'pull/initPull.c:128'),
    'pullInitPointPerVoxelSet': (_equalsOne, 0, b'pull', 'pull/initPull.c:147'),
    'pullInitGivenPosSet': (_equalsOne, 0, b'pull', 'pull/initPull.c:175'),
    'pullInitLiveThreshUseSet': (_equalsOne, 0, b'pull', 'pull/initPull.c:189'),
    'pullInitUnequalShapesAllowSet': (_equalsOne, 0, b'pull', 'pull/initPull.c:202'),
    'pullStart': (_equalsOne, 0, b'pull', 'pull/corePull.c:114'),
    'pullFinish': (_equalsOne, 0, b'pull', 'pull/corePull.c:169'),
    'pullRun': (_equalsOne, 0, b'pull', 'pull/corePull.c:337'),
    'pullEnergySpecParse': (_equalsOne, 0, b'pull', 'pull/energy.c:628'),
    'pullInfoSpecAdd': (_equalsOne, 0, b'pull', 'pull/infoPull.c:133'),
    'pullInfoGet': (_equalsOne, 0, b'pull', 'pull/infoPull.c:405'),
    'pullInfoSpecSprint': (_equalsOne, 0, b'pull', 'pull/infoPull.c:450'),
    'pullPointNew': ((lambda rv: _teem.ffi.NULL == rv), 0, b'pull', 'pull/pointPull.c:34'),
    'pullProbe': (_equalsOne, 0, b'pull', 'pull/pointPull.c:359'),
    'pullPointInitializePerVoxel': (_equalsOne, 0, b'pull', 'pull/pointPull.c:638'),
    'pullPointInitializeRandomOrHalton': (_equalsOne, 0, b'pull', 'pull/pointPull.c:823'),
    'pullPointInitializeGivenPos': (_equalsOne, 0, b'pull', 'pull/pointPull.c:992'),
    'pullVolumeSingleAdd': (_equalsOne, 0, b'pull', 'pull/volumePull.c:213'),
    'pullVolumeStackAdd': (_equalsOne, 0, b'pull', 'pull/volumePull.c:239'),
    'pullVolumeLookup': ((lambda rv: _teem.ffi.NULL == rv), 0, b'pull', 'pull/volumePull.c:478'),
    'pullConstraintScaleRange': (_equalsOne, 0, b'pull', 'pull/volumePull.c:497'),
    'pullCCFind': (_equalsOne, 0, b'pull', 'pull/ccPull.c:31'),
    'pullCCMeasure': (_equalsOne, 0, b'pull', 'pull/ccPull.c:115'),
    'pullCCSort': (_equalsOne, 0, b'pull', 'pull/ccPull.c:210'),
    'pullTraceSet': (_equalsOne, 0, b'pull', 'pull/trace.c:246'),
    'pullTraceMultiAdd': (_equalsOne, 0, b'pull', 'pull/trace.c:675'),
    'pullTraceMultiPlotAdd': (_equalsOne, 0, b'pull', 'pull/trace.c:705'),
    'pullTraceMultiWrite': (_equalsOne, 0, b'pull', 'pull/trace.c:1015'),
    'pullTraceMultiRead': (_equalsOne, 0, b'pull', 'pull/trace.c:1120'),
    'coilStart': (_equalsOne, 0, b'coil', 'coil/coreCoil.c:288'),
    'coilIterate': (_equalsOne, 0, b'coil', 'coil/coreCoil.c:363'),
    'coilFinish': (_equalsOne, 0, b'coil', 'coil/coreCoil.c:408'),
    'coilVolumeCheck': (_equalsOne, 0, b'coil', 'coil/methodsCoil.c:26'),
    'coilContextAllSet': (_equalsOne, 0, b'coil', 'coil/methodsCoil.c:70'),
    'coilOutputGet': (_equalsOne, 0, b'coil', 'coil/methodsCoil.c:201'),
    'pushOutputGet': (_equalsOne, 0, b'push', 'push/action.c:72'),
    'pushBinProcess': (_equalsOne, 0, b'push', 'push/action.c:162'),
    'pushBinPointAdd': (_equalsOne, 0, b'push', 'push/binning.c:181'),
    'pushRebin': (_equalsOne, 0, b'push', 'push/binning.c:198'),
    'pushStart': (_equalsOne, 0, b'push', 'push/corePush.c:184'),
    'pushIterate': (_equalsOne, 0, b'push', 'push/corePush.c:234'),
    'pushRun': (_equalsOne, 0, b'push', 'push/corePush.c:307'),
    'pushFinish': (_equalsOne, 0, b'push', 'push/corePush.c:397'),
    'pushEnergySpecParse': (_equalsOne, 0, b'push', 'push/forces.c:305'),
    'miteSample': ((lambda rv: math.isnan(rv)), 0, b'mite', 'mite/ray.c:152'),
    'miteRenderBegin': (_equalsOne, 0, b'mite', 'mite/renderMite.c:64'),
    'miteShadeSpecParse': (_equalsOne, 0, b'mite', 'mite/shade.c:70'),
    'miteThreadNew': ((lambda rv: _teem.ffi.NULL == rv), 0, b'mite', 'mite/thread.c:27'),
    'miteThreadBegin': (_equalsOne, 0, b'mite', 'mite/thread.c:93'),
    'miteVariableParse': (_equalsOne, 0, b'mite', 'mite/txf.c:102'),
    'miteNtxfCheck': (_equalsOne, 0, b'mite', 'mite/txf.c:233'),
    'meetAirEnumAllCheck': (_equalsOne, 0, b'meet', 'meet/enumall.c:227'),
    'meetNrrdKernelAllCheck': (_equalsOne, 0, b'meet', 'meet/meetNrrd.c:231'),
    'meetPullVolCopy': ((lambda rv: _teem.ffi.NULL == rv), 0, b'meet', 'meet/meetPull.c:45'),
    'meetPullVolParse': (_equalsOne, 0, b'meet', 'meet/meetPull.c:101'),
    'meetPullVolLeechable': (_equalsOne, 0, b'meet', 'meet/meetPull.c:313'),
    'meetPullVolStackBlurParmFinishMulti': (_equalsOne, 0, b'meet', 'meet/meetPull.c:426'),
    'meetPullVolLoadMulti': (_equalsOne, 0, b'meet', 'meet/meetPull.c:471'),
    'meetPullVolAddMulti': (_equalsOne, 0, b'meet', 'meet/meetPull.c:551'),
    'meetPullInfoParse': (_equalsOne, 0, b'meet', 'meet/meetPull.c:633'),
    'meetPullInfoAddMulti': (_equalsOne, 0, b'meet', 'meet/meetPull.c:764'),
}

# generates a biff-checking wrapper around function func
def _biffer(func, funcName: str, rvtf, mubi: int, bkey, fnln: str):
    def wrapper(*args):
        # pass all args to underlying C function; get return value rv
        rv = func(*args)
        # we have to get biff error if the returned value indicates error (rvtf(rv))
        # and, either: this function definitely uses biff (0 == mubi)
        #          or: (this function maybe uses biff and) "useBiff" args[mubi-1] is True
        if rvtf(rv) and (0 == mubi or args[mubi-1]):
            err = _teem.lib.biffGetDone(bkey)
            estr = ffi.string(err).decode('ascii').rstrip()
            _teem.lib.free(err)
            raise RuntimeError(f'return value {rv} from C function "{funcName}" ({fnln}):\n{estr}')
        return rv
    wrapper.__name__ = funcName
    wrapper.__doc__ = f"""
error-checking wrapper around C function "{funcName}" ({fnln}):
{func.__doc__}
"""
    return wrapper

# This traverses the actual symbols in the libteem used
for _symName in dir(_teem.lib):
    if 'free' == _symName:
        # don't export C runtime's free(), though we use it above in the biff wrapper
        continue
    _sym = getattr(_teem.lib, _symName)
    # Create a python object in this module for the library symbol _sym
    _exp = None
    # The exported symbol _sym is ...
    if not _symName in _biffDict:
        # ... either a function known to not use biff, or, not a function
        if str(_sym).startswith("<cdata 'airEnum *' "):
            # _sym is name of an airEnum, wrap it as such
            _exp = teemEnum(_sym)
        else:
            # straight copy of reference to _sym
            _exp = _sym
    else:
        # ... or a Python wrapper around a function known to use biff.
        (_rvtf, _mubi, _bkey, _fnln) = _biffDict[_symName]
        _exp = _biffer(_sym, _symName, _rvtf, _mubi, _bkey, _fnln)
    globals()[_symName] = _exp
