LIB = limn
HEADERS = limn.h
LIBOBJS = cam.o light.o obj.o io.o shapes.o matx.o methods.o qn.o
#TESTBINS = test/test
TESTBINS = test/tqn
BINS = 
BINLIBS = -lnrrd -llimn -lwash -llineal -lair -lbiff -lm

include ../make/Common.mk
