LIB = limn
HEADERS = limn.h
LIBOBJS = cam.o light.o obj.o io.o shapes.o matx.o methods.o qn.o
#TEST_BINS = test/test
TEST_BINS = test/tqn
BINS = 
#BINLIBS = -lnrrd -llimn -lwash -llineal -lair -lbiff -lm
BINLIBS = -llimn -lm

include ../make/Common.mk
