LIB = bane
HEADERS = bane.h
LIBOBJS = arrays.o methods.o range.o measr.o inc.o clip.o \
	hvol.o trnsf.o trex.o probe.o
TEST_BINS = test/apply test/gkms test/tinfo test/sigma test/pos \
	test/opac test/pvg
BINS = 
BINLIBS = -lbane -lnrrd -lbiff -lair -lm

include ../make/Common.mk
