#
# teem: Gordon Kindlmann's research software
# Copyright (C) 2002, 2001, 2000, 1999, 1998 University of Utah
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
#

LIB = echo
HEADERS = echo.h
PRIV_HEADERS = private.h
LIB_OBJS = methods.o enum.o object.o light.o render.o intx.o color.o
#TEST_BINS = test/proj1 test/mod4
#TEST_BINS = test/test test/trend
TEST_BINS = test/glyph
TEST_BINS = test/trend test/glyph
BINS = 
BIN_LIBS = -lten -lecho -llimn -ldye -lnrrd -lell -lbiff -lhest -lair -lm

include ../make/Common.mk
