#
# teem: Gordon Kindlmann's research software
# Copyright (C) 2002, 2001, 2000, 1999, 1998 University of Utah
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
#

LIB = hest
HEADERS = hest.h
PRIV_HEADERS = private.h
LIB_OBJS = defaults.o methods.o usage.o parse.o
TEST_BINS = test/ex0 test/ex1 test/ex2 test/ex3
TEST_BINS = test/ex3 test/ex4 test/ex5
BIN_LIBS = -lhest -lair -lm

include ../make/Common.mk
