/* The contents of this file are generated by CMake at configure-time, from
   the original at teem/CMake/airExistsConf.h, according to the results of
   running the stand-alone test program teem/CMake/TestAIR_EXISTS.c.
   For more details, search for AIR_EXISTS in teem/CMakeLists.txt */
#ifndef airExistsConf_h
#define airExistsConf_h
#cmakedefine AIR_EXISTS_MACRO_FAILS
#endif /* airExistsConf_h */
