IF(NOT Teem_FOUND)
  MESSAGE(FATAL_ERROR "Something went wrong. You are including TeemUse.cmake but Teem was not found")
ENDIF(NOT Teem_FOUND)

# Make Teem easier to use
INCLUDE_DIRECTORIES(${Teem_INCLUDE_DIRS})
LINK_DIRECTORIES(${Teem_LIBRARY_DIRS})

# Load the compiler settings used for Teem.
IF(Teem_BUILD_SETTINGS_FILE)
  INCLUDE(CMakeImportBuildSettings)
  CMAKE_IMPORT_BUILD_SETTINGS(${Teem_BUILD_SETTINGS_FILE})
ENDIF(Teem_BUILD_SETTINGS_FILE)

# Support static builds
IF(NOT Teem_BUILD_SHARED_LIBS)
  ADD_DEFINITIONS(-DTeem_STATIC=1)
ENDIF(NOT Teem_BUILD_SHARED_LIBS)

# Add compiler flags needed to use Teem.
SET(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${Teem_REQUIRED_C_FLAGS}")
SET(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} ${Teem_REQUIRED_EXE_LINKER_FLAGS}")
SET(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} ${Teem_REQUIRED_SHARED_LINKER_FLAGS}")
SET(CMAKE_MODULE_LINKER_FLAGS "${CMAKE_MODULE_LINKER_FLAGS} ${Teem_REQUIRED_MODULE_LINKER_FLAGS}")

